### PR TITLE
Ogenna esimai br user can see overview

### PR DESCRIPTION
**Pull request by ogennaesimai**

### CODE REVIEW

**Review by kanbi18 — CHANGES_REQUESTED** [review]
Your tasks button on the home fragment is to the YourTasks Fragment.

**Comment by ogennaesimai** [comment]
Okay. I shall set it up that way.

**Comment by ogennaesimai** [comment]
The fragments typically communicate with each other through a parent Activity except in special cases of dialog fragments or nested child fragments (details in guides). Since it is not one of the above special cases, it looks like YourTasks Fragment would need a parent Activity for it to be called from a button in HomeFragment.

**Comment by kanbi18** [comment]
> The fragments typically communicate with each other through a parent Activity except in special cases of dialog fragments or nested child fragments (details in guides). Since it is not one of the above special cases, it looks like YourTasks Fragment would need a parent Activity for it to be called from a button in HomeFragment.

https://stackoverflow.com/questions/23212162/how-to-move-from-one-fragment-to-another-fragment-on-click-of-an-imageview-in-an

this article has a method

**Comment by ogennaesimai** [comment]
Okay. I shall explore this method. Are you okay with me merging this for now and working on the new method in a subsequent pull? Committing to pull requests with Github has criteria and this pull request does not meet them all.

**Comment by kanbi18** [comment]
> Okay. I shall explore this method. Are you okay with me merging this for now and working on the new method in a subsequent pull? Committing to pull requests with Github has criteria and this pull request does not meet them all.

sure

**Comment by ogennaesimai** [comment]
Okay

**Pull request merged**
